package Model;
// Generated 29/10/2014 10:10:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Groups generated by hbm2java
 */
public class Groups  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Date created;
     private Date modified;

    public Groups() {
    }

	
    public Groups(String name) {
        this.name = name;
    }
    public Groups(String name, Date created, Date modified) {
       this.name = name;
       this.created = created;
       this.modified = modified;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }




}


