package Model;
// Generated 29/10/2014 10:10:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Posts generated by hbm2java
 */
public class Posts  implements java.io.Serializable {


     Integer id;
     int userId;
     String title;
     String body;
     Date created;
     Date modified;

    public Posts() {
    }

	
    public Posts(int userId, String title) {
        this.userId = userId;
        this.title = title;
    }
    public Posts(int userId, String title, String body, Date created, Date modified) {
       this.userId = userId;
       this.title = title;
       this.body = body;
       this.created = created;
       this.modified = modified;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }




}


